// Create Constants here
export const ALL_CUSTOMERS_REQUEST = "ALL_CUSTOMERS_REQUEST";
export const ALL_CUSTOMERS_SUCCESS = "ALL_CUSTOMERS_SUCCESS";
export const ALL_CUSTOMERS_FAIL = "ALL_CUSTOMERS_FAIL";
export const ALL_CUSTOMERS_CLEAR_ERRORS = "ALL_CUSTOMERS_CLEAR_ERRORS";

// Create Constants here
/* export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";
export const ALL_CUSTOMER_CLEAR_ERRORS = "ALL_CUSTOMER_CLEAR_ERRORS"; */

// Products Under Category

// Create Constants here
export const ALL_CATEGORIES_PRODUCT_REQUEST = "ALL_CATEGORIES_PRODUCT_REQUEST";
export const ALL_CATEGORIES_PRODUCT_SUCCESS = "ALL_CATEGORIES_PRODUCT_SUCCESS";
export const ALL_CATEGORIES_PRODUCT_FAIL = "ALL_CATEGORIES_PRODUCT_FAIL";

export const ALL_CATEGORIES_PRODUCT_CLEAR_ERRORS =
  "ALL_CATEGORIES_PRODUCT_CLEAR_ERRORS";
